stripe:
    publishable_key: pk_test_51NJzliIvExJPa5db0vyJudPUoRuMBWCj1u9IPiJo0Po13q7wEiCqtEFVjO1LtMTyQeWcFVrSLMEmj92RGubohUdv00KhQRt1bw
    secret_key: sk_test_51NJzliIvExJPa5dbZAeqcqfht6D6Z1D9RmLLAuTh81ho6hW20OjnBoENVQdIkKeu07HfGgpV0o5fPOm5ohkwaBuB00s2H3BTIF
